image: gitpod/workspace-java

tasks:
  - name: Build and Run
    init: |
      sudo apt update
      sudo apt install -y openjdk-17-jdk
      sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      java -version
      cd app
      mvn clean package
    command: docker-compose up

ports:
  - port: 8080
    onOpen: open-preview