image: gitpod/workspace-full

tasks:
  - name: Build and Run
    init: |
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.8-tem
      sdk use java 17.0.8-tem
      java -version
      cd app
      mvn clean package
    command: docker-compose up

ports:
  - port: 8080
    onOpen: open-preview